version: '3.11'

services:
  web:
    build: 
      context: ./src
      dockerfile: Dockerfile
    command: |
      bash -c 'alembic upgrade head;
      uvicorn app.main:app --reload --host 0.0.0.0 --port 8000'
    volumes:
      - './src:/app'
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
  
  db:
    image: postgres
    ports: 
      - 5432:5432
    environment:
      - PYTHONIOENCODING=utf-8
      - PGDATA=/var/lib/postgresql/data/data_maps_data/
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=data_maps
    restart: always