version: '3.11'

services:
  web:
    build: 
      context: ./src
      dockerfile: Dockerfile
    command: 'uvicorn app.main:app --reload --host 0.0.0.0 --port 8000'
    volumes:
      - './src:/app'
    ports:
      - 8000:8000
    env_file: ./src/.env
    depends_on:
      - db
    restart: always
  
  db:
    image: postgres
    ports: 
      - 8001:5432
    env_file: ./src/.env
    restart: always