version: '3.11'

services:
  web:
    build: 
      context: ./src
      dockerfile: Dockerfile
    command: 'uvicorn app.main:app --reload --host 0.0.0.0 --port 8000'
    volumes:
      - './src:/app'
    ports:
      - 8000:8000
    env_file: ./src/.env
    depends_on:
      - db
      - redis
    restart: always
    environment:
      - REDIS_URL=redis://eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81@redis:6379
  
  db:
    image: postgres
    ports: 
      - 5432:5432
    environment:
      - PYTHONIOENCODING=utf-8
      - PGDATA=/var/lib/postgresql/data/data_maps_data/
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=data_maps
    restart: always
    volumes:
      - cache:/data # use the named volume for db data
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel debug
    restart: always
    volumes:
      - cache:/data # use the same named volume for redis data
  
volumes:
  cache: # define the named volume here
    driver: local