"""init

Revision ID: 0501ef36677c
Revises: d1b26359fb84
Create Date: 2023-02-14 02:50:23.372285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0501ef36677c'
down_revision = 'd1b26359fb84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('census_variables', sa.Column('variable', sa.Text(), nullable=True))
    op.add_column('census_variables', sa.Column('section', sa.Text(), nullable=True))
    op.drop_column('census_variables', 'name')
    op.drop_column('census_variables', 'concept')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('census_variables', sa.Column('concept', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('census_variables', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('census_variables', 'section')
    op.drop_column('census_variables', 'variable')
    # ### end Alembic commands ###
