"""First migration

Revision ID: 3eccaa7988d3
Revises: 
Create Date: 2023-02-11 21:42:18.676312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eccaa7988d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('census_variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('concept', sa.Text(), nullable=True),
    sa.Column('group', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geographic_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geoid', sa.Text(), nullable=True),
    sa.Column('longitude', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geographic_types')
    op.drop_table('census_variables')
    # ### end Alembic commands ###
